// Code generated by cmd/reset. DO NOT EDIT.

package model

// Reset сбрасывает состояние Metrics к начальным значениям.
func (m *Metrics) Reset() {
	if m == nil {
		return
	}
	m.ID = ""
	m.MType = ""
	if m.Delta != nil {
		(*m.Delta) = 0
	}
	if m.Value != nil {
		(*m.Value) = 0
	}
	m.Hash = ""
}
