package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/token"
	"strings"
	"unicode"
)

// generatedHeader — шапка файла, по которой инструменты Go распознают сгенерированный код.
const generatedHeader = "// Code generated by cmd/reset. DO NOT EDIT."

// generatePackage формирует содержимое файла с методами Reset() для всех
// помеченных структур пакета и форматирует его по правилам gofmt.
func generatePackage(pkg *packageInfo) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "%s\n\npackage %s\n", generatedHeader, pkg.Name)

	for _, ms := range pkg.Marked {
		recv := receiverName(ms.Name)
		fmt.Fprintf(&buf, "\n// Reset сбрасывает состояние %s к начальным значениям.\n", ms.Name)
		fmt.Fprintf(&buf, "func (%s *%s) Reset() {\n", recv, ms.Name)
		fmt.Fprintf(&buf, "if %s == nil {\nreturn\n}\n", recv)
		for _, line := range pkg.structStmts(recv, ms.Type, map[string]bool{ms.Name: true}) {
			buf.WriteString(line)
			buf.WriteByte('\n')
		}
		buf.WriteString("}\n")
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("форматирование сгенерированного кода: %w", err)
	}
	return src, nil
}

// structStmts возвращает операторы сброса всех полей структуры st, доступной по выражению target.
// Множество visited защищает от бесконечной рекурсии при раскрытии взаимно вложенных типов.
func (p *packageInfo) structStmts(target string, st *ast.StructType, visited map[string]bool) []string {
	var stmts []string
	if st.Fields == nil {
		return stmts
	}
	for _, field := range st.Fields.List {
		names := fieldNames(field)
		for _, name := range names {
			if name == "_" {
				continue
			}
			stmts = append(stmts, p.fieldStmts(target+"."+name, field.Type, visited)...)
		}
	}
	return stmts
}

// fieldNames возвращает имена полей объявления, включая имя встроенного поля.
func fieldNames(field *ast.Field) []string {
	if len(field.Names) > 0 {
		names := make([]string, 0, len(field.Names))
		for _, ident := range field.Names {
			names = append(names, ident.Name)
		}
		return names
	}
	if name, ok := typeName(field.Type); ok {
		return []string{name}
	}
	return nil
}

// fieldStmts возвращает операторы сброса значения типа expr, доступного по выражению target.
func (p *packageInfo) fieldStmts(target string, expr ast.Expr, visited map[string]bool) []string {
	switch t := expr.(type) {
	case *ast.ParenExpr:
		return p.fieldStmts(target, t.X, visited)

	case *ast.StarExpr:
		return p.pointerStmts(target, t.X, visited)

	case *ast.ArrayType:
		if t.Len == nil {
			return []string{fmt.Sprintf("%s = %s[:0]", target, target)}
		}
		return []string{fmt.Sprintf("clear(%s[:])", target)}

	case *ast.MapType:
		return []string{fmt.Sprintf("clear(%s)", target)}

	case *ast.InterfaceType, *ast.ChanType, *ast.FuncType:
		return []string{fmt.Sprintf("%s = nil", target)}

	case *ast.StructType:
		return p.structStmts(target, t, visited)

	case *ast.Ident:
		return p.identStmts(target, t.Name, visited)

	case *ast.SelectorExpr, *ast.IndexExpr, *ast.IndexListExpr:
		// Тип объявлен в другом пакете или инстанцирован обобщённо:
		// без информации о типах остаётся безопасная проверка метода Reset().
		return []string{assertResetStmt("&" + target)}
	}
	return []string{fmt.Sprintf("// поле %s пропущено: неподдерживаемый тип %s", target, exprString(expr))}
}

// pointerStmts возвращает операторы сброса значения по указателю target, указывающему на тип pointee.
func (p *packageInfo) pointerStmts(target string, pointee ast.Expr, visited map[string]bool) []string {
	var inner []string
	switch t := unwrapParens(pointee).(type) {
	case *ast.Ident:
		switch {
		case p.Resetters[t.Name]:
			// Метод Reset() вызывается прямо на указателе.
			inner = []string{fmt.Sprintf("%s.Reset()", target)}
		default:
			inner = p.fieldStmts("(*"+target+")", t, visited)
		}
	case *ast.SelectorExpr, *ast.IndexExpr, *ast.IndexListExpr:
		inner = []string{assertResetStmt(target)}
	default:
		inner = p.fieldStmts("(*"+target+")", t, visited)
	}
	if len(inner) == 0 {
		return nil
	}
	stmts := make([]string, 0, len(inner)+2)
	stmts = append(stmts, fmt.Sprintf("if %s != nil {", target))
	stmts = append(stmts, inner...)
	stmts = append(stmts, "}")
	return stmts
}

// identStmts возвращает операторы сброса значения именованного типа name, доступного по выражению target.
func (p *packageInfo) identStmts(target, name string, visited map[string]bool) []string {
	if zero, ok := zeroValue(name); ok {
		return []string{fmt.Sprintf("%s = %s", target, zero)}
	}
	if p.Resetters[name] {
		return []string{fmt.Sprintf("%s.Reset()", target)}
	}
	underlying, ok := p.Underlying[name]
	if !ok {
		// Тип неизвестен (встроенный псевдоним или точечный импорт).
		return []string{assertResetStmt("&" + target)}
	}
	if visited[name] {
		return []string{fmt.Sprintf("// поле %s пропущено: рекурсивный тип %s без метода Reset()", target, name)}
	}
	visited[name] = true
	defer delete(visited, name)
	return p.fieldStmts(target, underlying, visited)
}

// assertResetStmt формирует проверку наличия метода Reset() у значения expr.
func assertResetStmt(expr string) string {
	return fmt.Sprintf("if resetter, ok := any(%s).(interface{ Reset() }); ok {\nresetter.Reset()\n}", expr)
}

// zeroValue возвращает литерал нулевого значения для предопределённого типа.
func zeroValue(name string) (string, bool) {
	switch name {
	case "bool":
		return "false", true
	case "string":
		return `""`, true
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune", "float32", "float64", "complex64", "complex128":
		return "0", true
	case "error", "any":
		return "nil", true
	}
	return "", false
}

// unwrapParens снимает с выражения внешние скобки.
func unwrapParens(expr ast.Expr) ast.Expr {
	for {
		paren, ok := expr.(*ast.ParenExpr)
		if !ok {
			return expr
		}
		expr = paren.X
	}
}

// receiverName подбирает короткое имя получателя по имени типа.
func receiverName(typeName string) string {
	var initials []rune
	for _, r := range typeName {
		if unicode.IsUpper(r) {
			initials = append(initials, unicode.ToLower(r))
		}
	}
	if len(initials) == 0 {
		initials = []rune{unicode.ToLower(rune(typeName[0]))}
	}
	if len(initials) > 3 {
		initials = initials[:3]
	}
	name := string(initials)
	if token.Lookup(name).IsKeyword() {
		return "r" + name
	}
	return name
}

// exprString печатает выражение типа в исходном виде для сообщений.
func exprString(expr ast.Expr) string {
	var buf strings.Builder
	if err := printer.Fprint(&buf, token.NewFileSet(), expr); err != nil {
		return "?"
	}
	return buf.String()
}
