// Code generated by cmd/reset. DO NOT EDIT.

package auditor

// Reset сбрасывает состояние AuditData к начальным значениям.
func (ad *AuditData) Reset() {
	if ad == nil {
		return
	}
	ad.IPAddress = ""
	ad.Metrics = ad.Metrics[:0]
	ad.TS = 0
}
